### ISSUE TITLE
ubuntu & tensorflow-rocm & anaconda 

### ISSUE THREAD

**Issue by YuriyTigiev** [RadeonOpenCompute/ROCm#1290]
How to install a tensorflow-rocm for an anaconda? 
conda-install trying to use old version of tensorflow-rocm from the cloud.

```
(ML) yuriy@PC-Ubuntu:~/Project$ conda install -c rocm tensorflow-rocm
Error processing line 1 of /home/yuriy/anaconda3/lib/python3.8/site-packages/google_auth-1.23.0-py3.8-nspkg.pth:

  Traceback (most recent call last):
    File "/home/yuriy/anaconda3/lib/python3.8/site.py", line 169, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "<frozen importlib._bootstrap>", line 553, in module_from_spec
  AttributeError: 'NoneType' object has no attribute 'loader'

Remainder of file ignored
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                                                     

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - tensorflow-rocm -> python[version='2.7.*|3.6.*|3.5.*']

Your python: python=3.8

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

```

**Comment by iHandle** [comment]
Activate your anaconda environment, then `pip install tensorflow-rocm`.

**Comment by YuriyTigiev** [comment]
Is it enough to install the tensorflow-rocm or I also should install the tensorflow? for simple code
Should I used 
`import tensorflow-rocm as tf`  instead of ` import tensorflow as tf` ?

**Comment by iHandle** [comment]
> Is it enough to install the tensorflow-rocm or I also should install the tensorflow? for simple code
> Should I used
> `import tensorflow-rocm as tf` instead of ` import tensorflow as tf` ?

It is enough to install just the `tensorflow-rocm`. Actually, I think there will be something wrong if you install both.

`import tensorflow as tf` is the correct to import.

**Comment by rkothako** [comment]
Yes, actually need to install conda install tenorflow-rocm in anaconda environment.
And then launch tf as import tensorflow as tf.

**Comment by rkothako** [comment]
Hi @YuriyTigiev 
Request to close this ticket if the answers are helpful.
Thank you.

**Comment by ROCmSupport** [comment]
Hi @YuriyTigiev
Request to close this ticket now.
Thank you.
