### ISSUE TITLE
4.3.1 release: fails to download source

### ISSUE THREAD

**Issue by gggh000** [RadeonOpenCompute/ROCm#1579]
Worked for earlier builds but not for 4.3.1
```
-
cd ~/ROCm-4.3.1 ; ~/bin/repo init -u https://github.com/RadeonOpenCompute/ROCm.git -b roc-4.3.1.x ; ~/bin/repo sync
-
fatal: Couldn't find remote ref refs/heads/roc-4.3.1.x
fatal: Couldn't find remote ref refs/heads/roc-4.3.1.x
manifests: sleeping 4.0 seconds before retrying
Downloading manifest from https://github.com/RadeonOpenCompute/ROCm.git
fatal: cannot obtain manifest https://github.com/RadeonOpenCompute/ROCm.git
Traceback (most recent call last):
  File "/root/ROCm-4.3.1/.repo/repo/main.py", line 651, in <module>
    _Main(sys.argv[1:])
  File "/root/ROCm-4.3.1/.repo/repo/main.py", line 627, in _Main
    result = run()
  File "/root/ROCm-4.3.1/.repo/repo/main.py", line 620, in <lambda>
    run = lambda: repo._Run(name, gopts, argv) or 0
  File "/root/ROCm-4.3.1/.repo/repo/main.py", line 286, in _Run
    result = cmd.Execute(copts, cargs)
  File "/root/ROCm-4.3.1/.repo/repo/subcmds/sync.py", line 969, in Execute
    self._UpdateManifestProject(opt, mp, manifest_name)
  File "/root/ROCm-4.3.1/.repo/repo/subcmds/sync.py", line 885, in _UpdateManifestProject
    partial_clone_exclude=self.manifest.PartialCloneExclude)
  File "/root/ROCm-4.3.1/.repo/repo/project.py", line 1133, in Sync_NetworkHalf
    and self._ApplyCloneBundle(initial=is_new, quiet=quiet, verbose=verbose)):
  File "/root/ROCm-4.3.1/.repo/repo/project.py", line 2275, in _ApplyCloneBundle
    bundle_url = remote.url + '/clone.bundle'
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
total 12
drwxr-xr-x  7 root root 4096 Sep 26 10:33 amdgpu
drwxr-xr-x  5 root root 4096 Dec 24  2020 amdgpu-pro
lrwxrwxrwx  1 root root   22 Sep 26 10:35 rocm -> /etc/alternatives/rocm
drwxr-xr-x 18 root root 4096 Sep 26 10:33 rocm-4.3.1
root@ixt-rack-70:/git.co/ad-hoc-scripts#

```

**Comment by xuhuisheng** [comment]
rocm-4.3.1 have no seperated branch, we could use master.

**Comment by ROCmSupport** [comment]
Hi @gggh000 
Thanks for reaching out.
I will check and get back very soon with information.
Thank you.

**Comment by ROCmSupport** [comment]
Hi @gggh000 
I got some information for you.
4.3.1 is minor release. The manifest is updated directly on master branch. 

To download source code, please use rocm-4.3.1 tag:
_repo init -u https://github.com/RadeonOpenCompute/ROCm.git -b refs/tags/rocm-4.3.1_

Hope this helps. Thank you.

**Comment by gggh000** [comment]
root@nonroot-Standard-PC-i440FX-PIIX-1996:~# repo init -u https://github.com/RadeonOpenCompute/ROCm.git -b refs/tags/rocm-4.3.1
Get https://gerrit.googlesource.com/git-repo/clone.bundle
Get https://gerrit.googlesource.com/git-repo
  File "/root/.repo/repo/main.py", line 79
    file=sys.stderr)
        ^
SyntaxError: invalid syntax
