### ISSUE TITLE
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by psi43** [RadeonOpenCompute/ROCm#442]
Hey, 

I've been using NVidia GPUs for a while now, but I wanted to try using an AMD GPU to see how they compare (and eventually switch to AMD due to NVidia's prices). 

I installed ROCm and the HelloWorld example ran through without any issues. Afterwards, I installed tensorflow-gpu and other dependencies of my machine learning project. When I try to run it, the following error comes up: 

```
Traceback (most recent call last):
  File "/home/oliverreipschlaeger/.local/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/oliverreipschlaeger/.local/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/oliverreipschlaeger/.local/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Object_detection_dir.py", line 22, in <module>
    import tensorflow as tf
  File "/home/oliverreipschlaeger/.local/lib/python3.5/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/oliverreipschlaeger/.local/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/oliverreipschlaeger/.local/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/oliverreipschlaeger/.local/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/oliverreipschlaeger/.local/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/oliverreipschlaeger/.local/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory
```

Now I googled to find out where to get the libcublas.so.9.0 file and found out that it's one of the files installed when installing NVidia CUDA. 
Do I need to install that despite using an AMD GPU? 

As for the hardware specs, I built my PC with the readme ( https://github.com/RadeonOpenCompute/ROCm ) in mind, so hardware shouldn't be the problem. 

I would really appreciate some pointers to what to do or what I did wrong. Thank you so much!

**Comment by briansp2020** [comment]
How did you install tensorflow? It seems like you are running CUDA compiled version. To run ROCm version of tensorflow, you need to download tensorflow whl file manually or build from source.
I have a write up on how to install tensorflow on ROCm (for an older version) but the idea is the same.
http://briansp2020.github.io/2017/11/05/fast_ai_ROCm/

The latest whl file released is tensorflow 1.3 at http://repo.radeon.com/rocm/misc/tensorflow/

**Comment by whchung** [comment]
/cc @parallelo for awareness

`tensorflow-gpu` on PyPI doesn't support AMD ROCm. As @briansp2020 mentioned please download TensorFlow 1.3 whl at http://repo.radeon.com/rocm/misc/tensorflow/ .

We are in the home stretch getting TensorFlow 1.8 released, whl package would be hosted on AMD website as well as PyPI.

**Comment by psi43** [comment]
Great, thank you @briansp2020 and @whchung. I'll try that first thing tomorrow. I just followed the instructions on how to get it to work, but I guess I must have missed that. Thank you! 

I think I saw the whl files about a week ago in the instructions but the link seemed to be dead. I'll try your suggestions, thanks a lot!

**Comment by briansp2020** [comment]
@whchung It's great to hear that 1.8 will be ready soon. What will the package be called? tensorflow-rocm?

**Comment by gstoner** [comment]
Operator Error,  closing issue
